version: '3.1'

services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: zeztra
      MONGO_INITDB_ROOT_PASSWORD: senhaforte123
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-dashboard
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: zeztra
      ME_CONFIG_MONGODB_ADMINPASSWORD: senhaforte123
      ME_CONFIG_MONGODB_URL: mongodb://zeztra:senhaforte123@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo